version: '3.8'
services:
  app:
    image: frontendcogenist  # Replace with your image name if different
    ports:
      - "3000:3000"              # Maps host port 3000 to container port 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped