version: '3.8'
services:
  app:
    image: frontendcogenist:latest
    ports:
      - "3000:3000"              
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped