services:
  app:
    image: sanantino/frontendcogenist:latest  # Update with your username
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - HOSTNAME=${HOSTNAME}
    restart: unless-stopped