version: '3.8'

services:
  app:
    image: sanantino/cogenist_frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.local  # Loads all variables from .env.local
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
