services:
  app:
    image: sanantino/cogenist_frontend:latest  # Use the pre-built image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - HOSTNAME=${HOSTNAME:-0.0.0.0}
      - NEXT_PUBLIC_AUTH_SECRET=${NEXT_PUBLIC_AUTH_SECRET}
      - NEXT_PUBLIC_RAZORPAY_KEY=${NEXT_PUBLIC_RAZORPAY_KEY}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_EMAILJS_SERVICE_ID=${NEXT_PUBLIC_EMAILJS_SERVICE_ID}
      - NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=${NEXT_PUBLIC_EMAILJS_TEMPLATE_ID}
      - NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=${NEXT_PUBLIC_EMAILJS_PUBLIC_KEY}
    env_file:
      - .env.local
    entrypoint: |
      sh -c "echo '---- Printing Environment Variables ----'; 
             echo 'NEXT_PUBLIC_AUTH_SECRET=' \$NEXT_PUBLIC_AUTH_SECRET; 
             echo 'NEXT_PUBLIC_RAZORPAY_KEY=' \$NEXT_PUBLIC_RAZORPAY_KEY; 
             echo 'NEXT_PUBLIC_BASE_URL=' \$NEXT_PUBLIC_BASE_URL; 
             echo 'NEXT_PUBLIC_EMAILJS_SERVICE_ID=' \$NEXT_PUBLIC_EMAILJS_SERVICE_ID; 
             echo 'NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=' \$NEXT_PUBLIC_EMAILJS_TEMPLATE_ID; 
             echo 'NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=' \$NEXT_PUBLIC_EMAILJS_PUBLIC_KEY; 
             echo 'NODE_ENV=' \$NODE_ENV; 
             echo 'PORT=' \$PORT; 
             echo 'HOSTNAME=' \$HOSTNAME; 
             echo '---- Running App ----'; 
             node server.js"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge