// src/components/plans.ts
import { Plan } from "@/interface/type";
import { FaGraduationCap, FaBrain, FaRocket } from "react-icons/fa";

export const plans: Plan[] = [
    {
      id: "basic",
      name: "Student Starter",
      price: "149",
      period: "monthly",
      description: "Kickstart your academic journey with essential tools!",
      features: [
        "1000+ doubts answered",
        "AI-generated 25+ Daily Time Tables",
        "10+ AI-generated Target & Weekly Study Plans",
        "1 Personal Mentorship Session",
        "Advanced Focus & Productivity Tools",
        "Smart Note Organization",
        "Email Support (24hr response)",
      ],
      icon: <FaGraduationCap className="h-12 w-12 text-blue-500" />,
      popular: false,
      color: "bg-gradient-to-br from-blue-100 via-teal-50 to-cyan-100 dark:from-blue-900 dark:via-teal-950 dark:to-cyan-900",
      buttonVariant: "outline",
      buttonText: "Get Started",
    },
    {
      id: "pro",
      name: "Academic Pro",
      price: "299",
      period: "monthly",
      description: "Level up with pro tools for top-tier performance!",
      features: [
        "Everything in Starter",
        "Unlimited Doubts Answered",
        "Unlimited AI-Generated Daily Time Tables",
        "20+ Targeted & Weekly Study Plans",
        "4 Personal Mentorship Sessions",
        "Full Access to Performance Analytics",
        "Complete Habit Tracker Access",
        "2000+ Practice Questions",
        "Full Access to All Workshops",
      ],
      icon: <FaBrain className="h-12 w-12 text-purple-500" />,
      popular: true,
      color: "bg-gradient-to-br from-purple-100 via-indigo-50 to-blue-100 dark:from-purple-900 dark:via-indigo-950 dark:to-blue-900",
      buttonVariant: "default",
      buttonText: "Join Pro",
    },
    {
      id: "ultimate",
      name: "Success Ultimate",
      price: "499",
      period: "monthly",
      description: "Unlock your full potential with ultimate support!",
      features: [
        "Everything in Pro",
        "Create Custom Test Series",
        "5 Personal Mentorship Sessions/Month",
        "5000+ Practice Questions",
        "Career Planning & Guidance",
        "24/7 Priority Support",
        "Personalized Learning Path",
      ],
      icon: <FaRocket className="h-12 w-12 text-orange-500" />,
      popular: false,
      color: "bg-gradient-to-br from-orange-100 via-amber-50 to-red-100 dark:from-orange-900 dark:via-amber-950 dark:to-red-900",
      buttonVariant: "outline",
      buttonText: "Go Ultimate",
    },
  ];