name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Debug file presence
        run: |
          pwd
          ls -la
          find . -name "docker-compose.*"

      - name: Create .env.local
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SOME_KEY: ${{ secrets.SOME_KEY }}
        run: |
          echo "NODE_ENV=$NODE_ENV" > .env.local
          echo "SOME_KEY=$SOME_KEY" >> .env.local
          ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

  deploy:
  needs: build-and-push
  runs-on: self-hosted
  if: github.event_name == 'push'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull image from Docker Hub
      run: docker pull sanantino/frontendcogenist:latest

    - name: Delete old container
      run: docker rm -f nextjs-app-container || true

    - name: Run Docker container
      run: docker run -d -p 3000:3000 --name nextjs-app-container sanantino/frontendcogenist:latest
      needs: build-and-push
      runs-on: self-hosted
      if: github.event_name == 'push'
      steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull image from Docker Hub
        run: docker pull frontendcogenist:latest

      - name: Delete old container
        run: docker rm -f nextjs-app-container || true

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name frontendcogenist:latest