name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Debug file presence
        run: |
          pwd
          ls -la
          find . -name "docker-compose.*"

      - name: Create .env.local
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}  # Example: "production"
          SOME_KEY: ${{ secrets.SOME_KEY }}  # Add your secrets
        run: |
          echo "NODE_ENV=$NODE_ENV" > .env.local
          echo "SOME_KEY=$SOME_KEY" >> .env.local
          ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create .env.local
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SOME_KEY: ${{ secrets.SOME_KEY }}
        run: |
          echo "NODE_ENV=$NODE_ENV" > .env.local
          echo "SOME_KEY=$SOME_KEY" >> .env.local
          ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy with Docker Compose
        run: |
          cd ${GITHUB_WORKSPACE}
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml up -d