name: Deploy Next.js Application

on:
  push:
    branches:
      - deploy-with-docker-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t integrationninjas/nextjs-app .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Publish Image to Docker Hub
        run: docker push integrationninjas/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull integrationninjas/nextjs-app:latest

      - name: Stop and Remove Old Container (If Exists)
        run: |
          docker stop nextjs-app-container || true
          docker rm nextjs-app-container || true  

      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 \
          --name nextjs-app-container \
          integrationninjas/nextjs-app

      - name: Verify Running Container
        run: docker ps -a
